version: '3.8'


services:
 server:
   build:
     context: ./server # Path to the backend Dockerfile
   ports:
     - "8000:8000"


 server2:
   build:
     context: ./server # Path to the backend Dockerfile
   ports:
     - "8001:8000"


 auth:
   build:
     context: ./auth # Path to the backend Dockerfile
   ports:
     - "5001:5001" 


 client1:
   build:
     context: ./client # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - server # Wait for backend service to be ready before starting frontend


 client2:
   build:
     context: ./client_2 # Path to the frontend Dockerfile
   ports:
     - "3001:3000"
   depends_on:
     - server2 # Wait for backend service to be ready before starting frontend